### PR TITLE
[INTG-1726] Add functionality to limit the number of inspections retrieved

### PR DESCRIPTION
**Pull request by phanikumarpatchigolla**
Adding this, so that we can lower the limit if there is any error due to heavy load.

### CODE REVIEW

**Comment by hkf57** [comment]
[boulder] we should 100% make the appropriate changes to readme:
* How these limits work, ie, how the limits are decided
* What scenarios should the user use these limits

**Comment by phanikumarpatchigolla** [comment]
> [boulder] we should 100% make the appropriate changes to readme:
> 
> * How these limits work, ie, how the limits are decided
> * What scenarios should the user use these limits

Agreed. But we do not know the exact error if it fails due to heavy load. So, I have uploaded the help page to give it a try by lowering the number if there is any error.

**Comment by phanikumarpatchigolla** [comment]
> > [boulder] we should 100% make the appropriate changes to readme:
> > 
> > * How these limits work, ie, how the limits are decided
> > * What scenarios should the user use these limits
> 
> Agreed. But we do not know the exact error if it fails due to heavy load. Apart from the timeout error, there can be some memory issues too. So, I have uploaded the help page to give it a try by lowering the number if there is any error.

https://github.com/SafetyCulture/iauditor-exporter/wiki/Errors

**Review by hkf57 — APPROVED** [review]
👍LGTM

**Pull request merged**
